# Demo-specific values
kviklet:
  # Reference the main chart's values
  image:
    tag: main

  service:
    annotations:
      cloud.google.com/backend-config: '{"default": "kviklet-demo-iap"}'

  externalSecretName: "kviklet-demo-config-secret" # Name of the secret containing the kviklets configuration

# GCP specific configuration
ingress:
  staticIpName: "kviklet-demo-ip" # Name of your static IP in GCP

# IAP configuration
iap:
  secretName: "kviklet-demo-oauth" # Secret containing OAuth client credentials

